export const MOCK_MACHINE_METRICS = {
  totalMachines: 120,
  onlineCount: 28,
  onlinePercent: '23.3%',
  inUseCount: 76,
  inUsePercent: '63.3%',
  reservedCount: 6,
  reservedPercent: '5.0%',
  maintenanceCount: 5,
  maintenancePercent: '4.2%',
  offlineCount: 5,
  offlinePercent: '4.2%'
};

export const MOCK_MACHINES = [
  {
    id: 'VIP-07',
    numericId: '07',
    ip: '192.168.1.107',
    port: 'Port #7',
    zoneId: 'zone-2',
    zoneName: 'Zone 2: VIP Suite',
    zoneIcon: 'hotel_class',
    cpu: 'i7-14700KF',
    gpu: 'RTX 4070 Ti Super 16GB',
    ram: '32GB DDR5',
    bootImage: 'Win11-Pro-Cyber-v25.02 (Cache: 0.18ms)',
    userName: 'Nguyễn Văn Nam',
    userRank: 'VIP Gold',
    userInitials: 'NM',
    currentGame: 'Valorant Ranked',
    sessionTime: '02h 15m / 04h 30m',
    status: 'in-use',
    statusLabel: 'Đang sử dụng',
    statusColor: 'sky'
  },
  {
    id: 'ESP-01',
    numericId: '01',
    ip: '192.168.1.10',
    port: '10Gbps Fiber',
    zoneId: 'zone-1',
    zoneName: 'Zone 1: Esports Arena',
    zoneIcon: 'military_tech',
    cpu: 'i9-14900K',
    gpu: 'RTX 4080 16GB',
    ram: 'ROG 360Hz',
    bootImage: 'Win11-Esports-Tournament-v3',
    userName: null,
    cleanStatus: 'Đã vệ sinh gear lúc 11:20',
    status: 'online',
    statusLabel: 'Online (Sẵn sàng)',
    statusColor: 'emerald'
  },
  {
    id: 'ESP-04',
    numericId: '04',
    ip: '192.168.1.14',
    port: 'Port #14',
    zoneId: 'zone-1',
    zoneName: 'Zone 1: Esports Arena',
    zoneIcon: 'military_tech',
    cpu: 'i9-14900K',
    gpu: 'RTX 4080 16GB',
    ram: '32GB DDR5',
    bootImage: 'Win11-Esports-Tournament-v3',
    userName: 'Hoàng Lâm',
    userRank: 'Team Scrim',
    userInitials: 'HL',
    currentGame: 'Bắt đầu: 14:30 chiều nay (Giữ chỗ 4h)',
    status: 'reserved',
    statusLabel: 'Đặt trước',
    statusColor: 'purple'
  },
  {
    id: 'ST-18',
    numericId: '18',
    ip: '192.168.2.18',
    port: 'Port Switch #04',
    zoneId: 'zone-3',
    zoneName: 'Zone 3: Tiêu Chuẩn',
    zoneIcon: 'dns',
    cpu: 'i5-13400F',
    gpu: 'RTX 4060 8GB',
    ram: '16GB DDR4',
    bootImage: 'SAN Read Drop: Rớt gói tin PXE boot',
    isWarningImage: true,
    userName: 'Đang kiểm tra phần cứng',
    cleanStatus: 'Lỗi Driver vGPU / Cáp LAN cổng #4',
    status: 'maintenance',
    statusLabel: 'Bảo trì',
    statusColor: 'rose'
  },
  {
    id: 'ST-22',
    numericId: '22',
    ip: '192.168.2.22',
    port: 'Không phản hồi',
    zoneId: 'zone-3',
    zoneName: 'Zone 3: Tiêu Chuẩn',
    zoneIcon: 'dns',
    cpu: 'i5-13400F',
    gpu: 'RTX 4060 8GB',
    ram: '16GB DDR4',
    bootImage: 'Trạng thái nguồn: Power Off',
    userName: 'Tắt nguồn',
    cleanStatus: 'Tắt lúc 04:12 sáng (Hết ca đêm)',
    status: 'offline',
    statusLabel: 'Offline',
    statusColor: 'slate'
  },
  {
    id: 'STR-02',
    numericId: '02',
    ip: '192.168.4.12',
    port: 'Dedicated Line',
    zoneId: 'zone-4',
    zoneName: 'Zone 4: Stream Studio',
    zoneIcon: 'videocam',
    cpu: 'i9-14900K',
    gpu: 'RTX 4090 24GB',
    ram: 'Cam 4K + GoXLR',
    bootImage: 'Win11-Creator-OBS-v25',
    userName: 'LinhNhiLive',
    userRank: 'LIVE',
    userInitials: 'LN',
    currentGame: 'OBS 4K Stream • TikTok/FB • 03h 10m',
    status: 'in-use',
    statusLabel: 'Đang sử dụng',
    statusColor: 'sky'
  },
  {
    id: 'CLOUD-08',
    numericId: '08',
    ip: '10.10.10.108',
    port: 'vGPU Slice 02',
    zoneId: 'zone-5',
    zoneName: 'Zone 5: Cloud Nodes',
    zoneIcon: 'cloud_sync',
    cpu: 'Dual AMD EPYC',
    gpu: 'RTX 4090 Cloud vGPU',
    ram: '128GB ECC',
    bootImage: 'WebRTC Latency: 1.1ms • AV1 Encode',
    userName: 'Khách App Remote #884',
    userRank: 'PWA Session',
    userInitials: 'CR',
    currentGame: 'Cyberpunk 2077 RT Overdrive • 00h 54m',
    status: 'in-use',
    statusLabel: 'Đang sử dụng',
    statusColor: 'sky'
  },
  {
    id: 'VIP-12',
    numericId: '12',
    ip: '192.168.1.112',
    port: 'Port #12',
    zoneId: 'zone-2',
    zoneName: 'Zone 2: VIP Suite',
    zoneIcon: 'hotel_class',
    cpu: 'i7-14700KF',
    gpu: 'RTX 4070 Ti Super 16GB',
    ram: '32GB DDR5',
    bootImage: 'Win11-Pro-Cyber-v25.02',
    userName: null,
    cleanStatus: 'Phòng VIP đơn, ghế bọc da cao cấp',
    status: 'online',
    statusLabel: 'Online (Sẵn sàng)',
    statusColor: 'emerald'
  }
];
