export const MOCK_MEMBER_METRICS = {
  totalMembers: 3420,
  totalGrowthPercent: '+12.4%',
  monthCreated: 142,
  activePlaying: 84,
  totalMachines: 120,
  capacityPercent: '70.0%',
  cloudNodes: 18,
  vipCount: 142,
  vipRevenueShare: '41.5%',
  vipDiamondCount: 24,
  shiftRevenue: 8450000,
  totalTransactions: 52,
  avgTransaction: '162.5k'
};

export const MOCK_MEMBERS = [
  {
    id: 1,
    uid: 'UID-08942',
    name: 'Nguyễn Văn Nam',
    email: 'nam.nv@cyber.vn',
    phone: '0912.345.678',
    username: 'nam.nv',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDL9Q6mN-0u2ODVotzbXDnvFioF4da-YYO3RkrzL8PgrnYfITQYMBbFwDAfqvqhXyoS2ofuTmgORHFX-eNOu-z1l6wG1AClmXrUICnYJ_JjYB-HRODcWvJUowfQAnRSBlvmYNNW-Pt2pae40M57JH1gPlZdTc4w4tFgrFe3sIXT9yWqcWIdpq64j-vSR0n2WAlQC_Z5I2ABvOwrGHQGhho8QHgN1eDSWFEGRtDIgiisxyddpf2ouPc',
    tier: 'gold',
    badge: 'verified',
    balance: 485000,
    balanceNote: '~ 24.2 giờ chơi',
    pts: 1250,
    status: 'playing',
    station: 'Playing Valorant',
    stationCode: 'VIP-07',
    stationDetail: 'Cloud Remote (RTX 4080 Node)',
    lastLoginTime: 'Hôm nay',
    lastLoginDetail: '10:24 AM',
    ipAddress: '192.168.1.107'
  },
  {
    id: 2,
    uid: 'UID-08943',
    name: 'Hoàng Long',
    email: 'long.hoang@esports.vn',
    phone: '0987.442.119',
    username: 'long_pro',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuArjxaFis5j7tv6CQR7R9iCj3z_TscHcW6bUxL4bJI_ZpV8gRgNR5cErT84YaWwxTg1CzNJWQ5fAPgTPjl-PdwvZyZTjs9KQ7i48cDJfRw9XiZz9ZNPryfsdpYhu1kaeE7oNwxHyTQZMHjSQi9l5W2pSEH_q9106BaIWYKcHlet8jyS7CUeOf2mLp0QERdBlpvOic54Ra0fnKHJe8hqs2ypz2aFsqX2LcrnBKgAmMG6xAn8zuxhGtc',
    tier: 'gold',
    badge: 'pro',
    balance: 1200000,
    balanceNote: '~ 60.0 giờ chơi',
    pts: 3400,
    status: 'playing',
    station: 'Playing CS 2',
    stationCode: 'ESP-01',
    stationDetail: 'Thi đấu 360Hz BenQ ZOWIE',
    lastLoginTime: 'Hôm nay',
    lastLoginDetail: '08:15 AM',
    ipAddress: '192.168.1.1'
  },
  {
    id: 3,
    uid: 'UID-07812',
    name: 'Trần Quốc Bảo',
    email: 'baotran99@gmail.com',
    phone: '0903.111.222',
    username: 'baotran99',
    avatar: '',
    initials: 'QB',
    tier: 'normal',
    badge: null,
    balance: 65000,
    balanceNote: '~ 4.3 giờ chơi',
    pts: 180,
    status: 'playing',
    station: 'Playing FC Online 4',
    stationCode: 'ST-05',
    stationDetail: 'Khu Tiêu Chuẩn Phổ Thông',
    lastLoginTime: 'Hôm nay',
    lastLoginDetail: '11:05 AM',
    ipAddress: '192.168.1.35'
  },
  {
    id: 4,
    uid: 'UID-06431',
    name: 'Lê Minh Khoa',
    email: 'khoa_cyber@yahoo.com',
    phone: '0945.666.777',
    username: 'khoa_cyber',
    avatar: '',
    initials: 'MK',
    tier: 'normal',
    badge: null,
    balance: 15000,
    balanceNote: '⚠️ Sắp hết tiền',
    pts: 45,
    status: 'offline',
    station: 'Máy trống',
    stationCode: null,
    stationDetail: null,
    lastLoginTime: 'Hôm qua',
    lastLoginDetail: '22:40 PM',
    ipAddress: null
  },
  {
    id: 5,
    uid: 'UID-09012',
    name: 'Phạm Thùy Linh',
    email: 'linh.stream@nexus.vn',
    phone: '0977.888.999',
    username: 'linh_stream',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDcpVxWKwtjPfNiNj3NJ5pt4--uJ6BfwNn_uZLUcjPpoFnM_YscnwPzmjFj9yJUdeKAt-_G27rJ686CIyvtOKL-e6pby30NvpmbDiV8iybYZ3eGivSln1w4qkG8vn8lRPLv6dbBtl_LiKnPGgJKDQHFftJ_DVaGNXT7vIF4a0xe_u4XpJCamZmxngl9ayYc2GpE_IObFgOtzAcyTA7Ciralk1_QWx7dC4mG-mmHr3CH1997TdIMeRw',
    tier: 'diamond',
    badge: 'streamer',
    balance: 890000,
    balanceNote: 'VIP Stream Suite',
    pts: 2800,
    status: 'playing',
    station: 'League of Legends',
    stationCode: 'STR-02',
    stationDetail: 'Phòng Stream Studio Cách Âm',
    lastLoginTime: 'Hôm nay',
    lastLoginDetail: '09:45 AM',
    ipAddress: '192.168.1.80'
  },
  {
    id: 6,
    uid: 'UID-05114',
    name: 'Đỗ Hải Đăng',
    email: 'dang.dh@gmail.com',
    phone: '0912.887.331',
    username: 'haidang_ban',
    avatar: '',
    initials: 'HD',
    tier: 'normal',
    badge: null,
    balance: 0,
    balanceNote: 'Tài khoản đóng băng',
    pts: 10,
    status: 'locked',
    station: 'Lý do: Vi phạm điều khoản gian lận 3rd-party',
    stationCode: null,
    stationDetail: null,
    lastLoginTime: '12/05/2025',
    lastLoginDetail: '14:12 PM',
    lockedBy: 'Khóa bởi Admin: #QHUY'
  }
];

export const INITIAL_MEMBERS = MOCK_MEMBERS;
