import React, { useState, useEffect } from 'react';
import { Monitor, X, Check, Cpu, Network } from 'lucide-react';
import machineService from '../../../shared/api/machine.service';

/**
 * CreateMachineModal Component
 * Adheres strictly to CSDL Computer & ComputerZone model schemas.
 * Auto-generates Machine Code (PC-xxx), Machine Name (Client Agent Windows Hostname / Máy xxx), LAN IP & PXE MAC.
 * Zero hardcoded text badges or static presets.
 */
export default function CreateMachineModal({ isOpen = false, onClose, onSubmit }) {
  const [zones, setZones] = useState([]);
  const [loadingZones, setLoadingZones] = useState(false);
  const [nextIdSuggestion, setNextIdSuggestion] = useState(37);

  const [formData, setFormData] = useState({
    isAutoCode: true,
    isAutoName: true,
    customCode: '',
    customName: '',
    zoneId: '',
    isAutoIp: true,
    isAutoMac: true,
    customIp: '',
    customMac: ''
  });

  // Fetch live zones and compute next machine ID suggestion on open
  useEffect(() => {
    if (isOpen) {
      const initModalData = async () => {
        setLoadingZones(true);
        try {
          const [zonesData, machinesData] = await Promise.all([
            machineService.getZones(),
            machineService.getMachines()
          ]);

          if (Array.isArray(machinesData)) {
            const maxId = machinesData.reduce(
              (max, m) => Math.max(max, Number(m.computer_id) || 0),
              0
            );
            setNextIdSuggestion(maxId + 1 || 37);
          }

          if (Array.isArray(zonesData) && zonesData.length > 0) {
            setZones(zonesData);
            setFormData((prev) => ({
              ...prev,
              zoneId: prev.zoneId || String(zonesData[0].zone_id)
            }));
          }
        } catch (err) {
          console.warn('Lỗi khi nạp dữ liệu khởi tạo modal:', err.message);
        } finally {
          setLoadingZones(false);
        }
      };
      initModalData();
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const autoGeneratedCode = `PC-${String(nextIdSuggestion).padStart(3, '0')}`;
  const autoGeneratedName = `Máy ${String(nextIdSuggestion).padStart(2, '0')}`;

  const selectedZone = zones.find(
    (z) => String(z.zone_id) === String(formData.zoneId) || `zone-${z.zone_id}` === formData.zoneId
  ) || zones[0];

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    const finalCode = formData.isAutoCode ? autoGeneratedCode : formData.customCode || autoGeneratedCode;
    const finalName = formData.isAutoName ? autoGeneratedName : formData.customName || finalCode;
    const finalIp = formData.isAutoIp ? '' : formData.customIp;
    const finalMac = formData.isAutoMac ? '' : formData.customMac;
    const targetZoneId = Number(String(formData.zoneId).replace('zone-', '')) || 1;

    if (onSubmit) {
      onSubmit({
        computer_name: finalName,
        code: finalCode,
        name: finalName,
        zone_id: targetZoneId,
        zoneId: `zone-${targetZoneId}`,
        ip: finalIp,
        ip_address: finalIp,
        mac_address: finalMac,
        is_remote_enabled: Boolean(selectedZone?.tier_level >= 3 || targetZoneId === 5)
      });
    }
    if (onClose) onClose();
  };

  return (
    <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-xs z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg overflow-hidden animate-in fade-in zoom-in-95 duration-150 border border-slate-200">
        {/* Header */}
        <div className="p-4 bg-slate-900 text-white flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-sky-500/20 border border-sky-400/30 text-sky-400 flex items-center justify-center shadow-xs">
              <Monitor className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-extrabold tracking-tight text-white leading-tight">
                Khai Báo Máy Trạm Mới
              </h3>
              <p className="text-xs text-slate-400">
                Tự động cấp phát Mã máy, Địa chỉ IP &amp; MAC
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="w-8 h-8 rounded-lg hover:bg-slate-800 text-slate-400 hover:text-white flex items-center justify-center transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form Body */}
        <form onSubmit={handleSubmit}>
          <div className="p-5 flex flex-col gap-4 text-xs font-semibold text-slate-700">
            {/* Row 1: Code & Machine Name (Auto-generated by default, toggleable) */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {/* Machine Code */}
              <div className="flex flex-col gap-1">
                <div className="flex items-center justify-between">
                  <label className="text-[11px] uppercase font-mono font-bold text-slate-600">
                    Mã Máy (Code) *
                  </label>
                  <label className="flex items-center gap-1 text-[10px] text-slate-500 cursor-pointer">
                    <input
                      type="checkbox"
                      name="isAutoCode"
                      checked={formData.isAutoCode}
                      onChange={handleChange}
                      className="rounded text-sky-600 accent-sky-600 cursor-pointer"
                    />
                    <span>Tự động</span>
                  </label>
                </div>
                {formData.isAutoCode ? (
                  <div className="px-3 py-2 bg-slate-200/80 rounded-xl font-mono text-xs text-slate-900 font-extrabold border border-slate-300">
                    {autoGeneratedCode}
                  </div>
                ) : (
                  <input
                    type="text"
                    name="customCode"
                    value={formData.customCode}
                    onChange={handleChange}
                    required
                    placeholder="VD: PC-037"
                    className="px-3 py-2 bg-white border border-slate-300 rounded-xl font-mono text-xs text-slate-900 font-extrabold focus:ring-2 focus:ring-sky-500/30 focus:outline-none"
                  />
                )}
              </div>

              {/* Machine Name */}
              <div className="flex flex-col gap-1">
                <div className="flex items-center justify-between">
                  <label className="text-[11px] uppercase font-mono font-bold text-slate-600">
                    Tên Máy Trạm *
                  </label>
                  <label className="flex items-center gap-1 text-[10px] text-slate-500 cursor-pointer">
                    <input
                      type="checkbox"
                      name="isAutoName"
                      checked={formData.isAutoName}
                      onChange={handleChange}
                      className="rounded text-sky-600 accent-sky-600 cursor-pointer"
                    />
                    <span>Tự động</span>
                  </label>
                </div>
                {formData.isAutoName ? (
                  <div className="px-3 py-2 bg-slate-200/80 rounded-xl text-xs text-slate-800 font-bold border border-slate-300 truncate" title={autoGeneratedName}>
                    {autoGeneratedName}
                  </div>
                ) : (
                  <input
                    type="text"
                    name="customName"
                    value={formData.customName}
                    onChange={handleChange}
                    placeholder="VD: Máy 37"
                    className="px-3 py-2 bg-white border border-slate-300 rounded-xl text-xs text-slate-900 font-bold focus:ring-2 focus:ring-sky-500/30 focus:outline-none"
                  />
                )}
              </div>
            </div>

            {/* Row 2: Dynamic Zone Selection */}
            <div className="flex flex-col gap-1">
              <label className="text-[11px] uppercase font-mono font-bold text-slate-600">
                Phân Khu &amp; Cấu Hình Phần Cứng *
              </label>

              {loadingZones ? (
                <div className="px-3 py-2 bg-slate-100 rounded-xl text-slate-500 font-mono text-xs flex items-center gap-2">
                  <span className="animate-spin">⏳</span> Đang tải danh sách phân khu...
                </div>
              ) : (
                <select
                  name="zoneId"
                  value={formData.zoneId}
                  onChange={handleChange}
                  className="px-3 py-2.5 bg-slate-50 border border-slate-300 rounded-xl text-xs text-slate-900 font-bold focus:bg-white focus:ring-2 focus:ring-sky-500/30 focus:outline-none cursor-pointer"
                >
                  {zones.map((z) => (
                    <option key={z.zone_id} value={z.zone_id}>
                      {z.zone_name} (Tier #{z.tier_level})
                    </option>
                  ))}
                </select>
              )}
            </div>

            {/* Hardware Description Card (Inherited directly from CSDL ComputerZone description) */}
            {selectedZone && (
              <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-xl flex items-center gap-3">
                <Cpu className="w-5 h-5 text-sky-600 shrink-0" />
                <div className="flex flex-col text-[11px]">
                  <span className="font-extrabold text-slate-900">{selectedZone.zone_name}</span>
                  <span className="text-slate-600 font-medium leading-relaxed">
                    {selectedZone.description || 'Cấu hình phần cứng mặc định của khu vực.'}
                  </span>
                </div>
              </div>
            )}

            {/* Row 3: IP & MAC Allocation (Auto by default) */}
            <div className="p-3.5 bg-slate-50 border border-slate-200/90 rounded-xl flex flex-col gap-3">
              <div className="flex items-center justify-between border-b pb-2">
                <span className="text-xs font-extrabold text-slate-800 flex items-center gap-1.5">
                  <Network className="w-4 h-4 text-sky-600" />
                  Cấu Hình Mạng LAN &amp; PXE Boot
                </span>
                <span className="text-[10px] font-mono text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded font-bold border border-emerald-200">
                  TỰ ĐỘNG CẤP PHÁT
                </span>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {/* IP Field */}
                <div className="flex flex-col gap-1">
                  <div className="flex items-center justify-between">
                    <label className="text-[11px] font-mono font-bold text-slate-600">Địa Chỉ IP</label>
                    <label className="flex items-center gap-1 text-[10px] text-slate-500 cursor-pointer">
                      <input
                        type="checkbox"
                        name="isAutoIp"
                        checked={formData.isAutoIp}
                        onChange={handleChange}
                        className="rounded text-sky-600 accent-sky-600 cursor-pointer"
                      />
                      <span>Tự động</span>
                    </label>
                  </div>
                  {formData.isAutoIp ? (
                    <div className="px-3 py-1.5 bg-slate-200/80 rounded-lg text-[11px] font-mono font-extrabold text-slate-600 border border-slate-300">
                      Auto LAN DHCP (192.168.1.x)
                    </div>
                  ) : (
                    <input
                      type="text"
                      name="customIp"
                      value={formData.customIp}
                      onChange={handleChange}
                      pattern="^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"
                      placeholder="192.168.1.104"
                      className="px-3 py-1.5 bg-white border border-slate-300 rounded-lg font-mono text-xs font-bold text-slate-900 focus:outline-none focus:ring-2 focus:ring-sky-500/30"
                    />
                  )}
                </div>

                {/* MAC Field */}
                <div className="flex flex-col gap-1">
                  <div className="flex items-center justify-between">
                    <label className="text-[11px] font-mono font-bold text-slate-600">Địa Chỉ MAC</label>
                    <label className="flex items-center gap-1 text-[10px] text-slate-500 cursor-pointer">
                      <input
                        type="checkbox"
                        name="isAutoMac"
                        checked={formData.isAutoMac}
                        onChange={handleChange}
                        className="rounded text-sky-600 accent-sky-600 cursor-pointer"
                      />
                      <span>Tự động</span>
                    </label>
                  </div>
                  {formData.isAutoMac ? (
                    <div className="px-3 py-1.5 bg-slate-200/80 rounded-lg text-[11px] font-mono font-extrabold text-slate-600 border border-slate-300">
                      Auto PXE MAC (F4:D4:88:5A:xx:xx)
                    </div>
                  ) : (
                    <input
                      type="text"
                      name="customMac"
                      value={formData.customMac}
                      onChange={handleChange}
                      pattern="^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"
                      placeholder="F4:D4:88:5A:01:04"
                      className="px-3 py-1.5 bg-white border border-slate-300 rounded-lg font-mono text-xs font-bold text-slate-900 focus:outline-none focus:ring-2 focus:ring-sky-500/30"
                    />
                  )}
                </div>
              </div>
            </div>
          </div>

          {/* Footer Action Buttons */}
          <div className="p-4 bg-slate-50 border-t border-slate-200 flex items-center justify-end gap-2">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 bg-slate-200 hover:bg-slate-300/80 text-slate-800 font-bold rounded-xl text-xs transition-colors cursor-pointer"
            >
              Hủy Bỏ
            </button>
            <button
              type="submit"
              className="px-5 py-2 bg-sky-600 hover:bg-sky-500 text-white font-extrabold rounded-xl text-xs shadow-md transition-colors flex items-center gap-1.5 cursor-pointer"
            >
              <Check className="w-4 h-4" />
              <span>Xác Nhận Tạo Máy</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
